### ISSUE TITLE
Where to Pass `trino.s3.credentials-provider` Parameter in Helm Chart?

### ISSUE THREAD

**Issue by arvind1705** [trinodb/charts#133]
I'm working with a Helm chart for deploying Trino and need to configure the `trino.s3.credentials-provider` parameter to use `com.amazonaws.auth.InstanceProfileCredentialsProvider` for S3 access.

Could someone please guide where to specify the `trino.s3.credentials-provider` parameter in the Helm chart configuration?
Any assistance would be appreciated!

**Comment by luismacosta** [comment]
Hi

To access s3, I'm using IAM role with serviceAccount
Create an IAM role + IAM policy to access s3
Define the role arn in [annotation](https://github.com/trinodb/charts/blob/main/charts/trino/templates/serviceaccount.yaml#L9)  _eks.amazonaws.com/role-arn_

**Comment by philicious** [comment]
```yaml
    serviceAccount:
      create: true
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/ROLE_NAME
```
