### ISSUE TITLE
UncheckedIOException: Failed to bind to /0.0.0.0:8443 when using HTTPS behind an Ingress

### ISSUE THREAD

**Issue by andrey-kondratov** [trinodb/charts#147]
### Summary
Cannot use TLS encryption b/w Ingress controller and the Service.

## Steps to reproduce
```yaml
server:
  config:
    https:
      enabled: true
service: 
  type: ClusterIP
  port: 8443
ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
```

## Expected result
The service created would be mapped to 8443 port of the pods, thus facilitating the TLS encryption between the Ingress controller and the Trino Coordinator Pod.

## Actual result
The port 8443 [is assigned](https://github.com/trinodb/charts/blob/3d4268caf76d5a2373006235dfe4275513ae14ab/charts/trino/templates/configmap-coordinator.yaml#L53) to `http-server.http.port`, which makes the process attempt to listen on the port twice, and ends up in an exception: 

> UncheckedIOException: Failed to bind to /0.0.0.0:8443

**Comment by andrey-kondratov** [comment]
A workaround is to disable HTTP server:

```yaml
  coordinatorExtraConfig: |
    http-server.http.enabled=false
  workerExtraConfig: | 
    http-server.http.enabled=false
```
