### ISSUE TITLE
Cannot overwrite table with non table for trino.coordinator.additionalJVMConfig and for trino.worker.additionalJVMConfig

### ISSUE THREAD

**Issue by adityatanwar03** [trinodb/charts#153]
Hi i think the additionalJVMConfig parameter in the values.yaml should be `additionalJVMConfig : [ ]` instead of `additionalJVMConfig: { }` which is producing this error / bug when doing helm install and upgrade 

Values i am using the additionalJVMConfig parameter :

```
coordinator:
  additionalJVMConfig:
    -  -Djava.security.auth.login.config=/etc/trino/config-files/conf.jaas
    -  -Djava.security.krb5.conf=/etc/trino/config-files/krb5.conf
```

Error / bug  i am getting :

`coalesce.go:286: warning: cannot overwrite table with non table for trino.coordinator.additionalJVMConfig (map[])`

Result : Despite of the above message the configmap is creating properly 

```[tasklist]
### Tasks
```

**Comment by heitorrbarros** [comment]
Hi @adityatanwar03!

I noticed that there might be a small issue with the type definition of trino.coordinator.additional JVM Config. To fix this, simply replace it with an array of strings, and your upgrade should work smoothly.

Would you mind testing it with the following values?

```yaml
coordinator:
  additionalJVMConfig:
    - "-Djava.security.auth.login.config=/etc/trino/config-files/conf.jaas"
    - "-Djava.security.krb5.conf=/etc/trino/config-files/krb5.conf"
```
