### ISSUE TITLE
Unable to set auth password in installation kubernetes, aready set https and shared-secret

### ISSUE THREAD

**Issue by hdavila146** [trinodb/charts#155]
Hello, I already set https behind a ingress with a cert, enable shared secret and configure a authentication type PASSWORD but still unable to set the configuration for password file. 
this is my current config values.yaml
```
image:
  tag: ""
server:
  workers: 3
  config:
    https:
      enabled: true
      port: 8443
      keystore:
        path: ""
    authenticationType: "PASSWORD"
auth:
  passwordAuth: "XXXX:XXXX"
  refreshPeriod: 1m
additionalConfigProperties:
    - "internal-communication.shared-secret=XXXX"
  
coordinator:
  secretMounts:
    - name: trino-password-authentication
      secretName: trino-file-authentication
      path: /etc/trino/auth
  jvm:
    maxHeapSize: "8G"
worker:
  jvm:
    maxHeapSize: "8G"
service:
  type: "NodePort"
  port: 8080 
ingress:
  enabled: true
  className: ""
  annotations:
    kubernetes.io/ingress.class: "nginx"
  hosts:
  - host: somedomain.com
    paths:
       - backend:
          service:
            name: trino-cluster
            port:
              number: 8080
         path: /
         pathType: Prefix
  - http:
    paths:   
       - backend:
          service:
            name: trino-cluster
            port:
              number: 8080
         path: /*
         pathType: ImplementationSpecific
  tls:
  - hosts:
    -  somedomain.com
    secretName: secret-tls
```
I got no errors just is not enable the auth by password in the login screen. of course XXXX are the password and user.
in the case creating the  password I followed this procedure 
Creating a password file[#](https://trino.io/docs/current/security/password-file.html#creating-a-password-file)
Password files utilizing the bcrypt format can be created using the [htpasswd](https://httpd.apache.org/docs/current/programs/htpasswd.html) utility from the [Apache HTTP Server](https://httpd.apache.org/). The cost must be specified, as Trino enforces a higher minimum cost than the default.

**Create an empty password file to get started:

touch password.db
Add or update the password for the user test:

htpasswd -B -C 10 password.db test**

and about the shared-secret I use 

**openssl rand 512 | base64**
