### ISSUE TITLE
It's not immediately obvious how the `additional*Properties` are supposed to be set

### ISSUE THREAD

**Issue by chgl** [trinodb/charts#166]
In the values.yaml the default value for setting additionalProperties is set as `{}`, suggesting that a dict object is expected: https://github.com/trinodb/charts/blob/main/charts/trino/values.yaml#L199-L207. However, in the templates this value is processed using `range` (https://github.com/trinodb/charts/blob/main/charts/trino/templates/configmap-coordinator.yaml#L62-L64) suggesting a list of values. In theory, using the same approach as when configuring the `additionalCatalog` (https://github.com/trinodb/charts/blob/533ace5fa38949254b20966604843b96d5955be4/charts/trino/templates/configmap-catalog.yaml#L22-L25) would work:

```yaml
additionalConfigProperties:
    new-properties: |
      internal-communication.shared-secret=${ENV:TRINO_SHARED_SECRET}
      http-server.process-forwarded=true
    more-properties: |
      web-ui.authentication.type=oauth2
```

However, the template is missing correct indentation (`nindent 4`). So instead one has to set the properties as a list:

```yaml
  additionalConfigProperties:
    - "internal-communication.shared-secret=${ENV:TRINO_SHARED_SECRET}"
    - "http-server.process-forwarded=true"
    - "web-ui.authentication.type=oauth2"
```

To make configuration more consistent I would suggest to either:

1. change the type of `additionalConfigProperties` to string so it can be configured as follows:
    ```yaml
      additionalConfigProperties: |
        internal-communication.shared-secret=${ENV:TRINO_SHARED_SECRET}
        http-server.process-forwarded=true
        web-ui.authentication.type=oauth2
    ```
2. Keep the type as-is, but fix the template to include `nindent 4`.

Personally, I'd prefer 1. since its more obvious how the string settings correspond to the trino properties. In 2. the nested `new-properties`, `more-properties` don't serve a purpose anyway.
