### ISSUE TITLE
Trino kubernetes with secrets

### ISSUE THREAD

**Issue by benedictmulongo** [trinodb/charts#274]
I have a problem using environement variables and secrets in Trino kubernetes. I have the following data in the `values.yaml` file:

```yaml
catalogs:
  tpch: |
    connector.name=tpch
    tpch.splits-per-node=4
  tpcds: |
    connector.name=tpcds
    tpcds.splits-per-node=4
  hive: |
    connector.name=hive
    fs.native-s3.enabled=true
    hive.metastore: file
    hive.metastore.catalog.dir: s3a://delta-lake-test/
    s3.aws-access-key=${MINIO_ACCESS_KEY}
    s3.aws-secret-key=${MINIO_SECRET_KEY}
    s3.endpoint=${MINIO_ENDPOINT_URL}
    s3.path-style-access=true

env:
- name: MINIO_ACCESS_KEY
  valueFrom:
    secretKeyRef:
      name: minio-credentials
      key: MINIO_ACCESS_KEY
- name: MINIO_SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: minio-credentials
      key: MINIO_SECRET_KEY
- name: MINIO_ENDPOINT_URL
  valueFrom:
    secretKeyRef:
      name: minio-credentials
      key: MINIO_ENDPOINT_URL

envFrom:
- secretRef:
    name: minio-credentials
```
and the config-map `configmap-catalog.yaml` created has the following data.

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog
  namespace: default
  labels:
    helm.sh/chart: trino-0.32.0
    app.kubernetes.io/name: trino
    app.kubernetes.io/instance: trino
    app.kubernetes.io/version: "461"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: catalogs
data:
  hive.properties: |
    connector.name=hive
    fs.native-s3.enabled=true
    hive.metastore: file
    hive.metastore.catalog.dir: s3a://delta-lake-test/
    s3.aws-access-key=${MINIO_ACCESS_KEY}
    s3.aws-secret-key=${MINIO_SECRET_KEY}
    s3.endpoint=${MINIO_ENDPOINT_URL}
    s3.path-style-access=true
    
  tpcds.properties: |
    connector.name=tpcds
    tpcds.splits-per-node=4
    
  tpch.properties: |
    connector.name=tpch
    tpch.splits-per-node=4
```

 The `hive.properties` file created on the pod is incorrect because the values are not replaced with the real values from the secret:

```conf
connector.name=hive
fs.native-s3.enabled=true
hive.metastore: file
hive.metastore.catalog.dir: s3a://delta-lake-test/
s3.aws-access-key=${MINIO_ACCESS_KEY}
s3.aws-secret-key=${MINIO_SECRET_KEY}
s3.endpoint=${MINIO_ENDPOINT_URL}
s3.path-style-access=true
```

Teh problems is the the following data in file `values.yaml` 

```yaml
  s3.aws-access-key=${MINIO_ACCESS_KEY}
  s3.aws-secret-key=${MINIO_SECRET_KEY}
  s3.endpoint=${MINIO_ENDPOINT_URL}
```
is not able to be replaced witht the real values from the secret or enviroment varibles, I have tried different possbility:
