### ISSUE TITLE
Helm upgrade failed for release trino/trino-gateway with chart trino-gateway@1.13.1: error validating "": error validating data: apiVersion not set

### ISSUE THREAD

**Issue by mkobusch** [trinodb/charts#288]
We encountered an error while attempting to upgrade the trino-gateway Helm release to version 1.13.1. The error message indicates that the apiVersion is not set.  

**Error Message:**
`Helm upgrade failed for release trino/trino-gateway with chart trino-gateway@1.13.1: error validating "": error validating data: apiVersion not set`

**Steps to Reproduce:**  
Ensure you have Helm installed and configured.
Update the HelmRelease resource to use version 1.13.1 of the trino-gateway chart:
```
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trino-gateway
  namespace: trino
spec:
  chart:
    spec:
      chart: charts/gateway
      version: "1.13.1"
      sourceRef:
        kind: GitRepository
        name: trino
        namespace: trino
  interval: 60m
  timeout: 5m
  releaseName: trino-gateway
  values:
    resources:
      limits:
        cpu: 1
        memory: 1Gi
      requests:
        cpu: 1
        memory: 1Gi
    image:
      repository: "<insert-gateway-image>"
      pullPolicy: IfNotPresent
      tag: "13"
    nameOverride: trino-gateway
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
      hosts:
        - host: <host-name>
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: trino-gateway-tls
          hosts:
            - <host-name>
    dataStoreSecret:
      name: "some-secret"
      key: "datastore.yaml"
    config:
      serverConfig:
        node.environment: production
        http-server.process-forwarded: true
      routingRules:
        rulesEngineEnabled: False
      dataStore:
        jdbcUrl:<mysql-db-url>
        user: <mysql-db-user>
        password: ""
        driver: com.mysql.cj.jdbc.Driver
      monitor:
        taskDelaySeconds: 10
      modules:
        - io.trino.gateway.ha.module.HaGatewayProviderModule
        - io.trino.gateway.ha.module.ClusterStateListenerModule
        - io.trino.gateway.ha.module.ClusterStatsMonitorModule
      managedApps:
        - io.trino.gateway.ha.clustermonitor.ActiveClusterMonitor
      clusterStatsConfiguration:
        monitorType: INFO_API
```
Apply the updated HelmRelease resource:
kubectl apply -f path-to-updated-helmrelease.yaml

**Expected Result:** The Helm release should upgrade successfully without any validation errors.  Actual Result: The upgrade fails with the error message indicating that the apiVersion is not set.  

**Workaround**: Reverting to the previous working version 1.13.0 allows the upgrade to proceed without issues.
