### ISSUE TITLE
Method to pass credentials in catalogs

### ISSUE THREAD

**Issue by hongbo-miao** [trinodb/charts#311]
Currently https://github.com/trinodb/charts/tree/c1bacab5b15a8ece6186a40ddd676f725b20a93b/charts/trino

does not document how to pass credentials such as

```yaml
catalogs:
  my_db: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://production-hm-postgres.xxxxxxxxxxxx.us-west-2.rds.amazonaws.com:5432/iot_db
    connection-user=xxx
    connection-password=xxx
```

It would be great to clarify how to pass credentials, thanks! ☺️

**Comment by nineinchnick** [comment]
Would you like to give it a shot and open a PR? We should add a comment with an example and reference https://trino.io/docs/current/security/secrets.html

**Comment by hongbo-miao** [comment]
Hi @nineinchnick how do we pass env? Seems right now it only supports `ConfigMap` (?)
We are using [Sealed Secret](https://github.com/bitnami-labs/sealed-secrets), which only supports `Secret`. I think this https://github.com/trinodb/charts/pull/297 may help us

**Comment by hongbo-miao** [comment]
Hi @nineinchnick hmm, based on my research, it seems right now it only supports `ConfigMap` to pass these envs (?)

```yaml
envFrom:
  - configMapRef:
      name: hm-trino-config-map
```
We are using [Sealed Secret](https://github.com/bitnami-labs/sealed-secrets), which only supports `Secret`. For example, even I provide `ConfigMap`

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hm-trino-config-map
  namespace: production-hm-trino
  annotations:
    # https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks
    argocd.argoproj.io/hook: PreSync
  labels:
    app.kubernetes.io/name: hm-trino-config-map
    app.kubernetes.io/part-of: production-hm-trino
stringData:
  POSTGRES_USER_NAME: xxx
  POSTGRES_PASSWORD: xxx
```

After it sealed, and deployed, it will become a `Secret` instead of `ConfigMap`.

I think if this https://github.com/trinodb/charts/pull/297 can be merged, it will help us 😃

**Comment by hongbo-miao** [comment]
Thanks for the link, @nineinchnick !

Assume I have `HM_POSTGRES_USER` and `HM_POSTGRES_PASSWORD` in a Kubernetes secret called `hm-trino-secret`.

I succeed by

```yaml
envFrom:
  - secretRef:
      name: hm-trino-secret
catalogs:
  postgresql: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://production-hm-postgres.xxxxxxxxxxxx.us-west-2.rds.amazonaws.com:5432/iot_db
    connection-user=${ENV:HM_POSTGRES_USER}
    connection-password=${ENV:HM_POSTGRES_PASSWORD}
```

I posted full deployment code at https://github.com/hongbo-miao/hongbomiao.com/pull/24997/files

Hope it can people some time in future! ☺️
