### ISSUE TITLE
Guide for how to use keda to auto scaling

### ISSUE THREAD

**Issue by hongbo-miao** [trinodb/charts#314]
It would be great to provide a guide for how to use Keda to auto scaling.

Currently I have Keda in my Kubernetes cluster. Here is my Trino values.yaml file:

```yaml
# ...
server:
  workers: 10
  keda:
    enabled: true
    pollingInterval: 30
    cooldownPeriod: 300
    initialCooldownPeriod: 0
    minReplicaCount: 0
    maxReplicaCount: 20
    triggers:
      - type: prometheus
        metricType: Value
        metadata:
          serverAddress: http://hm-mimir-query-frontend.production-hm-mimir.svc:8080/prometheus
          threshold: "1"
          metricName: required_workers
          query: >-
            sum by (service)
            (avg_over_time(trino_execution_ClusterSizeMonitor_RequiredWorkers{service={{ include "trino.fullname" . | quote }}}[5s]))
```

If I have

```
jmx:
  enabled: true
  exporter:
    enabled: true
```

and let Prometheus scrape it and write to Mimir.

Do I still need?

```
serviceMonitor:
  enabled: true
```

Sorry I am quite lost. 😞

**Comment by nineinchnick** [comment]
Are you using the Prometheus Operator? Then you need the service monitor. I'm not sure if we need a complete guide, or just reference Prometheus docs.

**Comment by hongbo-miao** [comment]
Thanks, @nineinchnick! I believe the ServiceMonitor approach and Direct Scraping are two different ways to write data to Prometheus, so we might only need one of them. Please correct me if I am wrong. Thanks!

```yaml
jmx:
  enabled: true
  exporter:
    enabled: true
serviceMonitor:
  enabled: false
```

or

```yaml
jmx:
  enabled: true
  exporter:
    enabled: false
serviceMonitor:
  enabled: true
```
