### ISSUE TITLE
[Trino] JMX Exporter Service Config

### ISSUE THREAD

**Issue by metalshanked** [trinodb/charts#317]
I am using the default JMX Exporter settings in the helm chart.
This springs up a sidecar standalone JMX container serving the metrics at `localhost:5556`

For accessing these metrics outside the cluster, a service or ingress needs to be setup
Is there a way to have the configs set so that it auto-creates an Ingress and/or Cluster IP, NodePort services?

Thanks!

```
jmx:
  coordinator: {}
  enabled: true
  exporter:
    configProperties: |-
      hostPort: localhost:{{- .Values.jmx.registryPort }}
      startDelaySeconds: 0
      ssl: false
      lowercaseOutputName: false
      lowercaseOutputLabelNames: false
      includeObjectNames: ["java.lang:type=Threading"]
      autoExcludeObjectNameAttributes: true
      excludeObjectNameAttributes:
        "java.lang:type=OperatingSystem":
          - "ObjectName"
        "java.lang:type=Runtime":
          - "ClassPath"
          - "SystemProperties"
      rules:
        - pattern: 'java\.lang<type=Threading><(.*)>ThreadCount: (.*)'
          name: java_lang_Threading_ThreadCount
          value: '$2'
          help: 'ThreadCount (java.lang<type=Threading><>ThreadCount)'
          type: UNTYPED
    enabled: true
    image: bitnami/jmx-exporter:1.0.1
    port: 5556
    pullPolicy: Always
    resources: {}
    securityContext: {}
  registryPort: 9080
  serverPort: 9081
  worker: {}
```
