### ISSUE TITLE
[gateway] Error rendering service template due to NOTES.txt

### ISSUE THREAD

**Issue by JustinObanor** [trinodb/charts#333]
With a service of type `LoadBalancer`, the helm chart fails to render due to an issue in the `NOTES.txt` file

Example values file
```
ingress:
  enabled: false

service:
  loadBalancerSourceRanges:
    - 11.1.1.1/11
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: https
      protocol: TCP
      port: 8443
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
```

Running with
```
helm template . -f values.yaml --debug
```

Results in the following error:
```
Error: template: test/templates/NOTES.txt:16:66: executing "test/templates/NOTES.txt" at <"port">: can't handle "port" for arg of type map[string]interface {}
helm.go:84: [debug] template: test/templates/NOTES.txt:16:66: executing "test/templates/NOTES.txt" at <"port">: can't handle "port" for arg of type map[string]interface {}
```

This is due the templating at: https://github.com/trinodb/charts/blob/main/charts/gateway/templates/NOTES.txt#L16

A possible fix would be to do this instead in the `NOTES.txt` file
```
{{- else if contains "LoadBalancer" .Values.service.type }}
     NOTE: It may take a few minutes for the LoadBalancer IP to be available.
           You can watch the status of by running 'kubectl get --namespace {{ .Release.Namespace }} svc -w trino-gateway'
  export SERVICE_IP=$(kubectl get svc --namespace {{ .Release.Namespace }} trino-gateway --template "{{"{{ range (index .status.loadBalancer.ingress 0) }}{{.}}{{ end }}"}}")
  echo http://$SERVICE_IP:'{{ index .Values.service.ports 0 "port" }}'
```
