### ISSUE TITLE
Add certificate to Trino trust store keeping already existed certificates

### ISSUE THREAD

**Issue by malcolm061990** [trinodb/charts#349]
Hi team
Some words about our infra:
- we use `1.39.0` chart
- trino is deployed in AWS EKS behind the load balancer (`http-server.process-forwarded=true` is set)
- iceberg tables are located in AWS s3 and used in trino

We need to configure **oauth2** authentication in Trino Web UI and keep **password** authentication for queries.
- Config №1 (removed non required code):
```yaml
config:
  authenticationType: "OAUTH2,PASSWORD"
server:
  coordinatorExtraConfig:
    web-ui.authentication.type=OAUTH2
    http-server.authentication.oauth2.issuer=https://internal-url.com/adfs
    http-server.authentication.oauth2.client-id=lient-id
    http-server.authentication.oauth2.client-secret=client-secret
```
In this case trino can't connect to oauth2.issuer URL https://internal-url.com/adfs because there is no required CA certificate for https://internal-url.com in trino truststore. Hence, SSO doesn't work

- config №2 (adding to config №1, thanks to [this](https://github.com/trinodb/charts/issues/132#issuecomment-2407337639) answer):
```yaml
coordinator:
  additionalJVMConfig:
    - "-Djavax.net.ssl.trustStore=/etc/jks/cacerts"
  additionalVolumes:
    - name: jks
      secret:
        secretName: trino-truststore-1
  additionalVolumeMounts:
    - name: jks
      mountPath: /etc/jks/cacerts
      subPath: cacerts
```
Here we overwrite the default trino truststore with new truststore which contains **only** required CA certificate for https://internal-url.com. In this case trino can't connect to AWS S3 (where Iceberg tables are stored) because of custom truststore doesn't have AWS S3 CA cert. Thats why trino queries were failed but SSO works

- config №3 (yaml code is same)
Here we copy default truststore file to some location (custom truststore file), import the `https://internal-url.com` CA into this new truststore file, create k8s secret (200k bytes) from this file and then use it in trino. In this case SSO and queries work well. But this is awkward as this new truststore file is duplicate of default truststore with just added our single CA cert:
```bash
# executed in trino-coordinator pod

# default truststore ontains 150 entries
$ keytool -list -keystore ${JAVA_HOME}/lib/security/cacerts
Your keystore contains 150 entries

# new trustore contains 151 cert (150 certs from default, one cert for https://internal-url.com which we imported manually)
$ keytool -list -keystore /etc/jks/cacerts
Your keystore contains 151 entries
```

Questions:
how to **add** the custom truststore **without** overwriting the default truststore (ie using two truststores)?
OR 
how to import custom cert in the **default** truststore? There are no permissions to import cert to default truststore now. Yes, we can create new docker image based on yours image and import cert there but its not the case
